### ISSUE TITLE
did:web support

### ISSUE THREAD

**Issue by stuartf** [digitalcredentials/issuer-coordinator#9]
I'd like to get this to feature parity with cred-admin and consolidate work here. I think the lowest hanging fruit is probably did:web support.

Any pointers on where to start, or thoughts about how to implement before I just dive in are appreciated.

**Comment by dmitrizagidulin** [comment]
@stuartf  - Thanks!
So, this repo (`issuer-coordinator`) itself does not deal with DIDs, it's just a coordinator that uses HTTP API calls to other services.

The code that deals with creating an IssuerInstance (with the signer function that is used to issue VCs) lives here: https://github.com/digitalcredentials/signing-service/blob/7169709b15d7f6976e702b97546a961f6f19a97e/src/issue.js#L10

So what you'll probably need to do is [add another config value](https://github.com/digitalcredentials/signing-service/blob/7169709b15d7f6976e702b97546a961f6f19a97e/src/issue.js#L5), something like `issuerDidMethod` (which would hold `key` or `web`). And then depending on the type, generate either a `did:key` from seed (which it already does), or [generate a `did:web`](https://github.com/interop-alliance/did-web-resolver#generating-from-seed), and in either case, create a `signingSuite` and proceed as normal.

Let me know if that helps (@jchartrand - jump in if I'm off base here)

**Comment by kayaelle** [comment]
@dmitrizagidulin @jchartrand - should I move this issue to https://github.com/digitalcredentials/signing-service ?

**Comment by dmitrizagidulin** [comment]
@kayaelle sure, that seems reasonable.

**Comment by stuartf** [comment]
@dmitrizagidulin any advice on getting a did-io driver for did:web? It looks like the did:key driver we're using (https://github.com/digitalcredentials/did-method-key) was forked from https://github.com/digitalbazaar/did-method-key but we don't have a https://github.com/digitalcredentials/did-method-web and https://github.com/digitalbazaar/did-method-web looks like it has a PR open to make it functional but also hasn't been updated in almost a year.

**Comment by dmitrizagidulin** [comment]
> @dmitrizagidulin any advice on getting a did-io driver for did:web? It looks like the did:key driver we're using (https://github.com/digitalcredentials/did-method-key) was forked from https://github.com/digitalbazaar/did-method-key but we don't have a https://github.com/digitalcredentials/did-method-web and https://github.com/digitalbazaar/did-method-web looks like it has a PR open to make it functional but also hasn't been updated in almost a year.

Much apologies for the delay. There is a did-io driver for `did:web` here: https://github.com/interop-alliance/did-web-resolver

I'd love to hop on a call and walk you through some of the details we'll need to change for issuer-coordinator, to support this.

**Comment by stuartf** [comment]
Great, I'll take a look at @interop/did-web-resolver

I'm free Monday or Tuesday afternoons next week if you want to do a call then.

**Comment by kayaelle** [comment]
Hey @stuartf & @dmitrizagidulin - how's this going?

**Comment by stuartf** [comment]
Hi @kayaelle I haven't had much time to dig into @interop/did-web-resolver hoping to get more into it before the end of the week.

**Comment by kayaelle** [comment]
Testing by @jchartrand w/micro-services in progress

**Comment by alexfigtree** [comment]
James says this can be closed
